TPCSystem/TPCSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tpcprocess.urls')),
]

TPCSystem/tpcprocess/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'tpcprocess'


urlpatterns = [

    # localhost/
    url(r'^$', views.login_user, name='login'),

    # /logout/
    url(r'^logout/$', views.logout_user, name='logout_user'),

    # /key/register_stu/
    url(r'^(?P<key>[0-1])/register_stu$', views.register_stu, name='register_stu'),

    # /submit_eligi/
    url(r'^submit_eligi/$', views.submit_eligi, name='submit_eligi'),

    # /comp_list/
    url(r'^comp_list/$', views.comp_list, name='comp_list'),

    # /apply/id
    url(r'^apply/(?P<company_id>[0-9]+)/$', views.apply, name='apply'),

    # /candi_list/
    url(r'^candi_list/$', views.candi_list, name='candi_list'),

    # /filter_list/
    url(r'^filter_candi/$', views.filter_candi, name='filter_candi'),

]

TPCSystem/tpcprocess/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    user = models.ForeignKey(User, default=1)
    u_id = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    branch = models.CharField(max_length=100)
    cgpa = models.CharField(max_length=100)
    live_kt = models.IntegerField()
    dead_kt = models.IntegerField()
    profile = models.TextField(max_length=4000)
    passing_year = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Company(models.Model):
    user = models.ForeignKey(User, default=1)
    c_id = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class EligiCriteria(models.Model):
    company = models.ForeignKey(Company, default=1)
    description = models.TextField(max_length=2000, null=True)
    tech_skills = models.TextField(max_length=2000, null=True)
    min_cgpa = models.CharField(max_length=100, null=True)
    live_kt_allowed = models.BooleanField(default=True)
    backlog_allowed = models.BooleanField(default=True)

    def __str__(self):
        return str(self.company) + ' Eligibility Criteria'


class CandidateList(models.Model):
    company = models.ForeignKey(Company, default=1)
    student = models.ForeignKey(Student, default=1)
    is_selected = models.BooleanField(default=False)

    def __str__(self):
        return str(self.company) + ' - ' + str(self.student)

TPCSystem/tpcprocess/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Student, Company


class UserForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if not password2:
            raise forms.ValidationError("You must confirm your password")
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match")
        return password2


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['name', 'u_id', 'branch', 'cgpa', 'live_kt', 'dead_kt', 'profile', 'passing_year']


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ['name', 'c_id', 'location']


class EligiForm(forms.Form):
    choices = ((True, 'YES'), (False, 'NO'))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': "mdl-textfield__input", 'rows': '5'}))
    cgpa_reqd = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'class': "mdl-textfield__input"}))
    live_kt = forms.ChoiceField(choices=choices, widget=forms.RadioSelect())
    dead_kt = forms.ChoiceField(choices=choices, widget=forms.RadioSelect())
    starting_sal = forms.FloatField()
    tech_skills = forms.CharField(widget=forms.Textarea(attrs={'class': "mdl-textfield__input", 'rows': '5'}))

TPCSystem/tpcprocess/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, logout, login
from .forms import UserForm, StudentForm, CompanyForm, EligiForm
from .models import Student, Company, EligiCriteria, CandidateList


def register_stu(request, key):
    form1 = UserForm(request.POST or None)
    print key
    if key == '0':
        form2 = StudentForm(request.POST or None)
    else:
        form2 = CompanyForm(request.POST or None)
    if form1.is_valid() and form2.is_valid():
        user = form1.save(commit=False)
        username = form1.cleaned_data['username']
        password = form1.cleaned_data['password1']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if key == '0':
                    stu = Student()
                    stu.user = request.user
                    stu.name = form2.cleaned_data['name']
                    stu.u_id = form2.cleaned_data['u_id']
                    stu.branch = form2.cleaned_data['branch']
                    stu.cgpa = form2.cleaned_data['cgpa']
                    stu.live_kt = form2.cleaned_data['live_kt']
                    stu.dead_kt = form2.cleaned_data['dead_kt']
                    stu.profile = form2.cleaned_data['profile']
                    stu.passing_year = form2.cleaned_data['passing_year']
                    stu.save()
                    companies = EligiCriteria.objects.all()
                    box_size = companies.count() * 60 + 300
                    context = {'companies': companies,
                               'box_size': box_size}
                    return render(request, 'tpcprocess/comp_list.html', context)
                else:
                    com = Company()
                    com.user = request.user
                    com.name = form2.cleaned_data['name']
                    com.location = form2.cleaned_data['location']
                    com.c_id = form2.cleaned_data['c_id']
                    com.save()
                    return render(request, 'tpcprocess/eligi_form.html')
    context = {'form1': form1, 'form2': form2}
    return render(request, 'tpcprocess/register_stu.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if Student.objects.filter(user=user).count() == 1:
                    companies = EligiCriteria.objects.all()
                    box_size = companies.count()*60 + 300
                    context = {'companies': companies,
                               'box_size': box_size}
                    return render(request, 'tpcprocess/comp_list.html', context)

                elif Company.objects.filter(user=user).count() == 1:
                    comp = get_object_or_404(Company, user=request.user)
                    count = comp.eligicriteria_set.count()
                    if count:
                        comp = get_object_or_404(EligiCriteria, company=comp)
                    context = {'filled': count, 'comp': comp}
                    return render(request, 'tpcprocess/eligi_form.html', context)
    return render(request, 'tpcprocess/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'tpcprocess/login.html', context)


def submit_eligi(request):
    if request.method == "POST":
        a = EligiCriteria()
        comp = get_object_or_404(Company, user=request.user)
        a.company = comp
        a.description = request.POST['description']
        a.min_cgpa = request.POST['cgpa']
        a.tech_skills = request.POST['techskill']
        if request.POST['ktoptions'] == 'False':
            a.live_kt_allowed = False
        else:
            a.live_kt_allowed = True
        if request.POST['bloptions'] == 'False':
            a.backlog_allowed = False
        else:
            a.backlog_allowed = True
        a.save()
        count = 1
        comp = get_object_or_404(EligiCriteria, company=comp)
        context = {'filled': count, 'comp': comp}
        return render(request, 'tpcprocess/eligi_form.html', context)
    else:
        comp = get_object_or_404(Company, user=request.user)
        count = comp.eligicriteria_set.count()
        if count:
            comp = get_object_or_404(EligiCriteria, company=comp)
        context = {'filled': count, 'comp': comp}
        return render(request, 'tpcprocess/eligi_form.html', context)


def comp_list(request):
    companies = EligiCriteria.objects.all()
    box_size = companies.count() * 60 + 300
    context = {'companies': companies,
               'box_size': box_size}
    return render(request, 'tpcprocess/comp_list.html', context)


def apply(request, company_id):
    a = get_object_or_404(EligiCriteria, pk=company_id)
    comp = a.company
    stu = get_object_or_404(Student, user=request.user)
    temp = CandidateList.objects.filter(company=comp, student=stu).count()
    if temp == 0:
        a = CandidateList()
        a.company = comp
        a.student = stu
        a.save()
    return comp_list(request)


def candi_list(request):
    company = get_object_or_404(Company, user=request.user)
    candidates = CandidateList.objects.filter(company=company)
    context = {'candidates': candidates}
    return render(request, 'tpcprocess/candi_list.html', context)


def filter_candi(request):
    if request.method == "POST":
        temp = request.POST.getlist('filterlist')
        for r in temp:
            a = get_object_or_404(CandidateList, pk=r)
            if a.is_selected:
                a.is_selected = False
            else:
                a.is_selected = True
            a.save()
    candidates = CandidateList.objects.filter(is_selected=True)
    context = {'candidates': candidates}
    return render(request, 'tpcprocess/filter_candi.html', context)

TPCSystem/tpcprocess/templates/tpcprocess/candi_list.html
{% extends 'tpcprocess/comp_base.html' %}

{% block body %}

<div class="container">
    <h2>Applied Candidates are : </h2>
    <br>
    <br>
    <form method="post" action="{% url 'tpcprocess:filter_candi' %}" enctype="multipart/form-data">
        {%csrf_token%}
        {% for candi in candidates %}
            <label for="{{candi.id}}" class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" >
                <input type="checkbox" id="{{candi.id}}" name="filterlist" class="mdl-checkbox__input" value="{{candi.id}}"
                       {% if candi.is_selected %} checked {% endif %}/>
                <span class="mdl-checkbox__label">{{candi.student.name}}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="mdl-checkbox__label">GPA : {{candi.student.cgpa}}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="mdl-checkbox__label">Branch : {{candi.student.branch}}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="mdl-checkbox__label">Live KTs : {{candi.student.live_kt}}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="mdl-checkbox__label">Dead KTs : {{candi.student.dead_kt}}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="mdl-checkbox__label">Profile : {{candi.student.profile}}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="mdl-checkbox__label">Pass Year : {{candi.student.passing_year}}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </label>
        {% endfor %}
        <br /><br /><br /><br />
        <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--purple-A700"
               value="Filter" style="left:45%" >
        <br />

    </form>
</div>

{% endblock %}

TPCSystem/tpcprocess/templates/tpcprocess/comp_base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Introducing Lollipop, a sweet new take on Android.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Eligibility Form</title>

    <!-- Page styles -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.0/material.min.css">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'tpcprocess/styles.css' %}">

    <script src="https://code.getmdl.io/1.2.0/material.min.js"></script>

<style>

</style>

</head>
	<body>
		<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

			<div class="android-header mdl-layout__header mdl-layout__header--waterfall">
				<div class="mdl-layout__header-row">
					<span class="android-title mdl-layout-title">
						<a class="mdl-typography--text-uppercase">Barclays</a>
					</span>
					<!-- Add spacer, to align navigation to the right in desktop -->
					<div class="android-header-spacer mdl-layout-spacer"></div>
					<!-- Navigation -->
					<div class="android-navigation-container">
						<nav class="android-navigation mdl-navigation">
							<a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'tpcprocess:submit_eligi' %}">eligibility form</a>
							<a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'tpcprocess:candi_list' %}">Candidate list</a>
							<a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'tpcprocess:filter_candi' %}">Filtered List</a>
							<a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'tpcprocess:logout_user' %}">Log Out</a>
						</nav>
					</div>
				</div>
			</div>
			{% block body %}
			{% endblock %}
		</div>


	</body>
</html>

TPCSystem/tpcprocess/templates/tpcprocess/comp_list.html
{% extends 'tpcprocess/stu_base.html' %}

{% block body %}

    <div class="container">
        <h3>Recruiting Companies</h3>
        <p>Click for further details</p>

        <style>
            .demo-accordion-4 {
                height: {{box_size}}px;
                border: 1px solid white;
            }
            .demo-accordion-4 .mdlext-accordion__tabpanel {
                background-color: rgba(165, 214, 167, 0.4);
            }

        </style>

        <ul class="mdlext-accordion mdlext-js-accordion mdlext-accordion--vertical demo-accordion-4" role="tablist" aria-multiselectable="false">
            {% for comp in companies %}
                <li class="mdlext-accordion__panel" role="presentation">
                    <header class="mdlext-accordion__tab" aria-expanded="false" role="tab">
                        <i class="material-icons">business</i>
                        <span class="mdlext-accordion__tab__caption">{{comp.company.name}}</span>
                        <i class="mdlext-aria-toggle-material-icons"></i>
                    </header>
                    <section class="mdlext-accordion__tabpanel" role="tabpanel">
                        <h5>{{comp.company.location}}</h5>
                        <p>{{comp.description}}</p>
                        <p>Technical Skills Expected : {{comp.tech_skills}}</p>
                        <p>Minimum CGPA Expected : {{comp.min_cgpa}}</p>
                        <p>Live KT Allowed : {% if comp.live_kt_allowed %} Yes {% else %} No {% endif%}</p>
                        <p>Backlogs Allowed : {% if comp.bl_allowed %} Yes {% else %} No {% endif%}</p>

                        <a href="{% url 'tpcprocess:apply' comp.id %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
                            style="float:right;margin-right:20px">
                            APPLY
                        </a>
                    </section>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

TPCSystem/tpcprocess/templates/tpcprocess/eligi_form.html
{% extends 'tpcprocess/comp_base.html' %}

{% block body %}

{% if filled == 1 %}
    <div class="container">
    <br><br><br>
    <h2>Company Eligibility Criteria has been set</h2>
    <br>
    <h4>Description : {{comp.description}}</h4>
    <h4>Tech Skills : {{comp.tech_skills}}</h4>
    <h4>Min CGPA : {{comp.min_cgpa}}</h4>
    <h4>Live KT allowed : {{comp.live_kt_allowed}}</h4>
    <h4>Backlog allowed : {{comp.backlog_allowed}}</h4>
    </div>

{% else %}
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--10-col mdl-cell--1-offset" style="margin-top:50px;">
        <form method="post" action="{% url 'tpcprocess:submit_eligi' %}" enctype="multipart/form-data">
            {%csrf_token%}
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<textarea class="mdl-textfield__input" type="text" rows= "5" name="description" id="desc"></textarea>
				<label class="mdl-textfield__label mdl-color-text--black" for="desc">Description</label>
            </div>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" name="cgpa" id="cgpa">
                <label class="mdl-textfield__label mdl-color-text--black" for="cgpa">Minimum CGPA Required</label>
            </div>
            <br>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<textarea class="mdl-textfield__input" type="text" rows= "5" name="techskill" id="tech"></textarea>
				<label class="mdl-textfield__label mdl-color-text--black" for="tech">Technical Skills required</label>
            </div>

            <br />
            <br />
            <p style="font-size:20px">Live KT Permitted :</p>
            <label for="ktoption-1" class="mdl-radio mdl-js-radio mdl-js-ripple-effect">
                <input type="radio" class="mdl-radio__button" id="ktoption-1" name="ktoptions" value="True" checked />
                <span class="mdl-radio__label">Yes</span>
            </label>
            <label for="ktoption-2" class="mdl-radio mdl-js-radio mdl-js-ripple-effect">
                <input type="radio" class="mdl-radio__button" id="ktoption-2" name="ktoptions" value="False" />
                <span class="mdl-radio__label">No</span>
            </label>

            <br />
            <br />
            <p style="font-size:20px">Backlogs Permitted :</p>
            <label for="bloption-1" class="mdl-radio mdl-js-radio mdl-js-ripple-effect">
                <input type="radio" class="mdl-radio__button" id="bloption-1" name="bloptions" value="True" checked />
                <span class="mdl-radio__label">Yes</span>
            </label>
            <label for="bloption-2" class="mdl-radio mdl-js-radio mdl-js-ripple-effect">
                <input type="radio" class="mdl-radio__button" id="bloption-2" name="bloptions" value="False" />
                <span class="mdl-radio__label">No</span>
            </label>
            <br />
            <br />
            <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--purple-A700"
                   value="Submit" style="left:20%" >
            <br />

        </form>
    </div>
</div>

{% endif %}
{% endblock %}

TPCSystem/tpcprocess/templates/tpcprocess/login.html
<!doctype html>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="Introducing Lollipop, a sweet new take on Android.">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
		<title>TPC</title>

        {% load staticfiles %}
		<!-- Page styles -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://code.getmdl.io/1.2.0/material.min.css">
		<link rel="stylesheet" href="styles.css">

		<script src="https://code.getmdl.io/1.2.0/material.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

		<style>
			body {
				color: white;
			}
			.login-box {
				<!--background-color:#fafafa;-->
				color:black;
				border-radius:5px;
				padding-bottom:20px;
			}
		</style>

	</head>
	<body class="mdl-color--purple-A700">

		<div class="mdl-grid" style="padding:30px;">
			<div class="mdl-cell mdl-cell--4-col mdl-cell--4-offset">
			</div>
		</div>

		<div class="mdl-grid">
			<div class="mdl-cell mdl-cell--6-col mdl-cell--3-offset" >
				<center>
				<h4>Welcome to</h4>
				<h2>Training and Placement Cell</h2>
				</center>
			</div>
		</div>

		<div class="mdl-grid mdl-cell mdl-cell--4-col mdl-cell--4-offset login-box mdl-shadow--6dp mdl-color--grey-100">

			<form action="{% url 'tpcprocess:login' %}" method="post" enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="left:10%">
                    <label class="mdl-textfield__label mdl-color-text--black" for="user">Username</label>
                    <input class="mdl-textfield__input mdl-color-text--black" name="username" type="text" id="user">
                </div>

                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="left:10%">
                    <label class="mdl-textfield__label mdl-color-text--black" for="pass">Password</label>
                    <input class="mdl-textfield__input mdl-color-text--black" name="password" type="password" id="pass">
                </div>
                <br />
                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--purple-A700"
                            id="loginButton" value="Login" style="left:35%" >
                <br />
			</form>


		</div>

        <div>
        <br />
            <a href="{% url 'tpcprocess:register_stu' 0 %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--brown-800"
               style="left:39%" >
                Student Reg
            </a> &nbsp;&nbsp;&nbsp;
            <a href="{% url 'tpcprocess:register_stu' 1 %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent mdl-color--brown-800"
               style="left:39%" >
                Company Reg
            </a>
        </div>

	</body>
</html>

TPCSystem/tpcprocess/templates/tpcprocess/stu_base.html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="Introducing Lollipop, a sweet new take on Android.">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
		<title>Student Home</title>

		<!-- Page styles -->
        {% load staticfiles %}
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.4/dialog-polyfill.css">
		<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
		<link rel="stylesheet" href="{% static 'tpcprocess/mdl-ext-eqjs.min.css' %}">
		<link rel="stylesheet" href="{% static 'tpcprocess/styles.css' %}">

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="https://code.getmdl.io/1.2.0/material.min.js"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.4/dialog-polyfill.css" type="text/javascript" charset="utf-8"></script>
		<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
		<script src="https://code.getmdl.io/1.1.3/material.min.js" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'tpcprocess/eq.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'tpcprocess/mdl-ext.min.js' %}" type="text/javascript" charset="utf-8"></script>

		<style>

		body {
			background-color:EBCAF3;
		}
		</style>
	</head>

	<body>

		<style>
			.mdl-layout__header-row {
				background-color:009688;
			}
		</style>
		<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

			<div class="android-header mdl-layout__header mdl-layout__header--waterfall">
				<div class="mdl-layout__header-row">

					<!-- Add spacer, to align navigation to the right in desktop -->
					<div class="android-header-spacer mdl-layout-spacer"></div>
					<!-- Navigation -->
					<div class="android-navigation-container">
						<nav class="android-navigation mdl-navigation">
							<a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'tpcprocess:comp_list' %}">Companies</a>
							<a class="mdl-navigation__link mdl-typography--text-uppercase" href="#">Status </a>
							<a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'tpcprocess:logout_user' %}">Log Out </a>
						</nav>
					</div>
				</div>
			</div>

            {% block body%}
            {% endblock %}
		</div>

	</body>
</html>